export const LIMITS = {
  MAX: {
    WORKSPACE_TITLE_CHARACTER: 32,
    WORKSPACE_DESC_CHARACTER: 96,
    WORKSPACE_THUMBNAIL_IMAGE_SIZE: 4096, // in megabytes
    WORKSPACE_SINGLECOLOR_COLOR_LENGTH: 7, // hex #ff0000
    WORKSPACE_GRADIENT_COLOR_LENGTH: 7,
    WORKSPACES: 20, // max workspaces
  },
  MIN: {
    WORKSPACE_TITLE_CHARACTER: 3,
  },
};
