export const LIMITS = {
  MAX: {
    WORKSPACE_TITLE_CHARACTER_LENGTH: 32,
    WORKSPACE_DESC_CHARACTER_LENGTH: 48,
    WORKSPACE_THUMBNAIL_IMAGE_SIZE: 4096, // in megabytes
    WORKSPACE_SINGLECOLOR_COLOR_LENGTH: 7, // hex #ff0000
    WORKSPACE_GRADIENT_COLOR_LENGTH: 7,
    WORKSPACES: 20, // max workspaces
    WORKSPACE_FIELD_TITLE_CHARACTER_LENGTH: 28,
    WORKSPACE_CARD_COLOR_CHARACTER_LENGTH: 7,
    WORKSPACE_CARD_TITLE_CHARACTER_LENGTH: 40,
    WORKSPACE_CARD_DESC_CHARACTER_LENGTH: 356,
    WORKSPACE_CARD_TAGS_CHARACTER_LENGTH: 10,
    WORKSPACE_CARD_LENGTH: 20, // max cards
    WORKSPACE_FIELD_LENGTH: 20, // max fields
  },
  MIN: {
    WORKSPACE_TITLE_CHARACTER_LENGTH: 0,
    WORKSPACE_FIELD_TITLE_CHARACTER_LENGTH: 2,
    WORKSPACE_CARD_TITLE_CHARACTER_LENGTH: 3,
    WORKSPACE_CARD_DESC_CHARACTER_LENGTH: 0,
    WORKSPACE_CARD_TAGS_CHARACTER_LENGTH: 0,
  },
};
